[theme]
primaryColor = "#6366F1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
# Disable file watching to prevent inotify errors on cloud
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[runner]
fastReruns = false
enforceSerializableSessionState = false
